import { INoticias } from "./INoticias";

export const noticiasJSON : INoticias[] = [
    {
        id: 0,
        name: "Código Laboral Dominicano: una conquista social que debemos reformar",
        description: "De nuestro código laboral, podemos resaltar varios aspectos que de acuerdo con los tiempos en que vivimos deben ser revisados, es importante reconocer como el desempleo constituye una fuente de inseguridad e inestabilidad económica en países en vía de desarrollo como la República Dominicana.",
        img: "",
        date: "domingo, 24 de septiembre 2023 | 10:42 pm",
        link: "https://elnuevodiario.com.do/codigo-laboral-dominicano-una-conquista-social-que-debemos-reformar/",
    },
    {
        id: 1,
        name: "Digitalización servicios municipales: Iniciativa para prevenir lavado de activos, evasión fiscal y eficientizar servicios públicos",
        description: "La República Dominicana, así como el resto de los países del mundo, luego del Covid-19, transita por retos y desafíos propios de un contexto de transformación que es cada vez más apresurado. Este proceso de transformación es realmente amplio, por lo que la presente reflexión estará enfocada en la transformación digital de los ayuntamientos y su repercusión en la evasión fiscal, el lavado de activos y el acceso a servicios de calidad en la administración pública.",
        img: "",
        date: "domingo, 24 de septiembre 2023 | 10:42 pm",
        link: "https://elnuevodiario.com.do/digitalizacion-servicios-municipales-iniciativa-para-prevenir-lavado-de-activos-evasion-fiscal-y-eficientizar-servicios-publicos/ ",
    },
    {
        id: 2,
        name: " Inversión extranjera directa en la zona especial de desarrollo fronterizo",
        description: "La inversión extranjera es una de las herramientas fundamentales con la que cuenta una nación para alcanzar el desarrollo, de manera particular, en países con recursos limitados para el emprendimiento en industrias, no sólo grandes, sino sofisticadas desde el punto de vista de la transferencia de tecnología y del know how.",
        img: "",
        date: "domingo, 24 de septiembre 2023 | 10:42 pm",
        link: "https://elnuevodiario.com.do/inversion-extranjera-directa-en-la-zona-especial-de-desarrollo-fronterizo/",
    },
    {
        id:3,
        name: "Mutatis Mutandis: Gobernar para transformar",
        description: "Introducción: El término en latín ¨mutatis mutandis¨ significa cambiando lo que se debe cambiar. Si aterrizamos esto al contexto del desarrollo de una nación, podemos interpretar que en un mundo y una sociedad que está en constante cambio, se necesita un gobierno que se mantenga actualizado en cuanto a los avances tecnológicos e innovadores de la economía, y haga los cambios y transformaciones de lugar necesarios para la evolución.",
        img: "",
        date: "domingo, 24 de septiembre 2023 | 10:42 pm",
        link: "https://elnuevodiario.com.do/mutatis-mutandis-gobernar-para-transformar/",
    },
    {
        id:4,
        name: "Elecciones Presidenciales RD 2024: Quién gana, quién pierde y de qué depende",
        description: "Según una publicación realizada por la Universidad de Navarra en 1988, en la que se citan los comentarios hechos por Alfredo Cruz Prados acerca de la clásica obra de Aristóteles sobre «La Política», «La democracia surge cuando los hombres creen que, por ser iguales en algo (en la libertad), son iguales absolutamente y exigen por ello una participación igual en todas las cosas. Tanto los demócratas como los oligarcas ‘tienen cierta justicia, pero en términos absolutos yerran'».",
        img: "",
        date: "domingo, 24 de septiembre 2023 | 10:42 pm",
        link: "https://elnuevodiario.com.do/elecciones-presidenciales-rd-2024-quien-gana-quien-pierde-y-de-que-depende/",
    },
    {
        id:5,
        name: "Creación y adecuación de normas para nuevos modelos de negocios: evolucionando a los tiempos de la innovación",
        description: "En la medida en que los pueblos evolucionan, regularmente surge la necesidad de crear y adecuar leyes encauzadas a garantizar la convivencia en los diferentes ámbitos de la sociedad. En algunas ocasiones esas adecuaciones están orientadas al área socioeconómica, lo que a veces puede resultar disruptivo, sin embargo, eso en modo alguno indica que crear y/o adecuar normas no vaya a garantizar el equilibrio y buen funcionamiento de los sectores impactados.",
        img: "",
        date: "domingo, 24 de septiembre 2023 | 10:42 pm",
        link: "https://elnuevodiario.com.do/creacion-y-adecuacion-de-normas-para-nuevos-modelos-de-negocios-evolucionando-a-los-tiempos-de-la-innovacion/",
    },
    {
        id:6,
        name: "Digitalización servicios municipales: Iniciativa para prevenir lavado de activos, evasión fiscal y eficientizar servicios públicos",
        description: "La República Dominicana, así como el resto de los países del mundo, luego del Covid-19, transita por retos y desafíos propios de un contexto de transformación que es cada vez más apresurado. Este proceso de transformación es realmente amplio, por lo que la presente reflexión estará enfocada en la transformación digital de los ayuntamientos y su repercusión en la evasión fiscal, el lavado de activos y el acceso a servicios de calidad en la administración pública.",
        img: "logo.png",
        date: "domingo, 24 de septiembre 2023 | 10:42 pm",
        link: "https://elnuevodiario.com.do/digitalizacion-servicios-municipales-iniciativa-para-prevenir-lavado-de-activos-evasion-fiscal-y-eficientizar-servicios-publicos/",
    },
];